### ISSUE TITLE
i cannot install it in syfmony 2.6

### ISSUE THREAD

**Issue by jiyongcheng** [tasmanianfox/MpdfPortBundle#15]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tfox/mpdf-port-bundle could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for symfony/framework-standard-edition 2.6.x-dev -> satisfiable by symfony/framework-standard-edition[2.6.x-dev].
    - symfony/framework-standard-edition 2.6.x-dev requires tfox/mpdf-port-bundle dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by tasmanianfox** [comment]
I've just tried to install the latest version of MPdfPortBundle with symfony 2.6 and here are my dependencies in composer.json file:
```
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "tfox/mpdf-port-bundle": "^1.2"
    },
```
Everything was fine with this configuration. Could you try to install MpdfPortBundle using the string provided below?
```
 "tfox/mpdf-port-bundle": "^1.2"
```
