### ISSUE TITLE
mpdf version

### ISSUE THREAD

**Issue by marcel-burkhard** [tasmanianfox/MpdfPortBundle#17]
Composer.json requires mPDF >=5.7

Now this means it actually started installing mPDF 6.x which has some BC breaks.

Can you tag a version that requires mPDF 5.* ?

I didn't submit a PR because it could now break those new applications that already integrated mPDF 6.x functions.

Thanks.

**Comment by tasmanianfox** [comment]
Thanks for sending an issue. Fixed it, now the bundle requires Mpdf v. 5.7.4

**Comment by marcel-burkhard** [comment]
Thank you.

Btw 6.x is already stable too so it would probably make sense to start a 1.3 branch with that?
