### ISSUE TITLE
mPdf Version

### ISSUE THREAD

**Issue by acpbytron** [tasmanianfox/MpdfPortBundle#22]
Would there be an issue with updating the mpdf dependency version to 6.1.* ?  In this version there is a dependency on the "setasign/fpdi": "1.6.*" which allows for the use of the commercial pdf parser to merge pdf with a version > 1.4.

**Comment by garak** [comment]
:+1: 
use `^6.0` instead of `6.0.*`

**Comment by tasmanianfox** [comment]
Sorry for late reply. I updated dependencies, so Composer will download mPdf v6.1.1 with the bundle by default.

@garak thanks for tip!
