### ISSUE TITLE
Not able to download pdf

### ISSUE THREAD

**Issue by sivakaza-volyty** [tasmanianfox/MpdfPortBundle#24]
I have a custom action (generate pdf) in my sonata admin. below is my code, If i remove the download related code then the browser is rendering pdf perfectly. But Failed to download the file. 

     public function generatePdfAction(){
          $request = $this->getRequest();
          $id = $request->get($this->admin->getIdParameter());

          $object = $this->admin->getObject($id);

          if (!$object) {
              throw $this->createNotFoundException(sprintf('unable to find the object with id : %s', $id));
          }

          $this->admin->checkAccess('edit', $object);

          $this->admin->setSubject($object);

          $datagrid = $this->admin->getDatagrid();
          $formView = $datagrid->getForm()->createView();

          $em = $this->getDoctrine()->getManager();
          $orderItems = $em->getRepository('AppBundle:OrderItem')->getOrderItemsOfMerchant($object->getMerchant(), $object->getStartDate(), $object->getEndDate() );

          $orderItemsTotal = $em->getRepository('AppBundle:OrderItem')->getOrderItemsTotal($orderItems, $object->getMerchant()->getId());

        define('_MPDF_TTFONTDATAPATH','downloads/payout/');

        $html = $this->renderView('AppBundle:PayoutAdmin:pdf.html.twig', array(
            'action' => 'Generate Pdf',
            'object' => $object,
            'form'   => $formView,
            'orderItems' => $orderItems,
            'orderItemsTotal' => $orderItemsTotal,
            'elements' => $this->admin->getShow(),
        ), null);

        $fileName = $object->getMerchant() . '_' . $object->getStartDate()->format('m-d-y') . '_to_' . $object->getEndDate()->format('m-d-y');

        $mpdfService = $this->get('tfox.mpdfport');
        //return $mpdfService->generatePdfResponse(mb_convert_encoding($html, 'UTF-8', 'UTF-8'));

        return new Response($mpdfService->generatePdf(mb_convert_encoding($html, 'UTF-8', 'UTF-8')),
            array(
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => sprintf('attachment; filename="'.$fileName.'"')
            )
        );

    }

getting the following error

`Unable to find template "" (looked into: /home/user/projects/myproject/app/Resources/views, /home/user/projects/myproject/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, /home/user/projects/myproject/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views).
500 Internal Server Error - InvalidArgumentException
1 linked Exception: Twig_Error_Loader »`

**Comment by tasmanianfox** [comment]
I think that the second argument (HTTP status) argument is missing here, so the correct code should look like:
```
    return new Response($mpdfService->generatePdf(mb_convert_encoding($html, 'UTF-8', 'UTF-8')),
        200,
        array(
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => sprintf('attachment; filename="'.$fileName.'"')
        )
    );
```

Definition of the Response class constructor is here:
http://api.symfony.com/2.8/Symfony/Component/HttpFoundation/Response.html#method___construct
`
__construct(mixed $content = '', int $status = 200, array $headers = array())
`

**Comment by sivakaza-volyty** [comment]
Tried but no luck still getting the same error Message. No idea where i'm missing some thing. BTW my version of Symfony is 2.7.x.

**Comment by tasmanianfox** [comment]
May be, there is some problem that isn't described in the error message (I had similar issues with this bundle). Could you try to surround this code with try .. catch?

```
try {
    $response = new Response($mpdfService->generatePdf(mb_convert_encoding($html, 'UTF-8', 'UTF-8')),
        200,
        array(
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => sprintf('attachment; filename="'.$fileName.'"')
        )
    );
    return $response;
} catch(\Exception $e) {
  printf($e->getMessage());
  die;
}
```
So you'll check if the problem actually related to template

**Comment by sivakaza-volyty** [comment]
@tasmanianfox Thanks for your quick reply. Sry to say It is not going to catch block. It is breaking some where in the try only and getting the same err msg.

**Comment by tasmanianfox** [comment]
Okay. Actually, I suspect that there is a problem with download-response, because, as you said, you have no problems with rendering PDF in browser

Could you try two codes below?
```
$mpdfService->generatePdf(mb_convert_encoding($html, 'UTF-8', 'UTF-8')
return Response('');
```

```
$mpdfService->generatePdf(mb_convert_encoding('Hello World!', 'UTF-8', 'UTF-8')
return Response('');
```
I would like to check if generatePdf() method throws an error or not. If not, you'll get an empty page.

**Comment by sivakaza-volyty** [comment]
@tasmanianfox Resolved the issue. My code is below. Don't know weather my approach is correct or not.

        $response = $mpdfService->generatePdf(mb_convert_encoding($html, 'UTF-8', 'UTF-8'));
        try {
            file_put_contents('downloads/payout/' . $fileName, $response);
            $response = new BinaryFileResponse('downloads/payout/' . $fileName);
            $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT);

            return $response;

        }catch(\Exception $e) {
            printf($e->getMessage());
            die;
        }

**Comment by tasmanianfox** [comment]
BinaryFileResponse is a good option. Please note that your PDF file remains on your disk after user downloads it. The more PDF files you generate, the more space consumes 'downloads/payout/' directory. I may recommend to use temporary files, something like:
```
$file = tmpfile();
$path = stream_get_meta_data($file)['uri']; // eg: /tmp/phpFx0513a, source: http://stackoverflow.com/a/16487120
file_put_contents($path, $response);
$response = new BinaryFileResponse($path);
$response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT);
return $response;
```
(I didn't tested this code, sorry)
A temporary file will be deleted automatically right after sending response to client.

**Comment by sivakaza-volyty** [comment]
@tasmanianfox Thanks for the Great idea, i'll implement that.
