### ISSUE TITLE
PDF file does not contain CSS style

### ISSUE THREAD

**Issue by ketavc** [tasmanianfox/MpdfPortBundle#26]
I'm using your library for generating pdf file from dynamic html file.

The HTML looks nice with css effect, But when i convert html to pdf. The PDF will not contain proper css effect.

Below is my code:

`$pathToPdf = $this->container->getParameter("pdf_upload_dir") . $name;
  $mpdfService = $this->container->get('tfox.mpdfport');
  $response = $mpdfService->generatePdf($html);
  file_put_contents($pathToPdf, $response);
  chmod($pathToPdf,0777);`

PDF file will save at destination folder but without css effect.

See Screen shots of both
Below is HTML file
![e ticket](https://cloud.githubusercontent.com/assets/7146539/21590564/0cc40606-d123-11e6-96c0-08c97ec5a73f.png)

Below is PDF file
![selection_003](https://cloud.githubusercontent.com/assets/7146539/21590597/59a16fa4-d123-11e6-9c59-36490b4be8a4.png)

**Comment by msmosso** [comment]
Hi,

I am facing the same problem.

Thanks in advance,
Matheus

**Comment by pabgaran** [comment]
I think this is a topic for the main library, not for this bundle.

Check here -> https://mpdf.github.io/css-stylesheets/introduction.html
