### ISSUE TITLE
Change in timezone after generate PDF

### ISSUE THREAD

**Issue by ketavchotaliya** [tasmanianfox/MpdfPortBundle#27]
Hello,
I'm using your library for generating PDF from html. Before generate Pdf Timezone is Asia/Kolkata, But after generating Pdf timezone is change to Europe/London.

Below is my code:

`      print_r(new \DateTime()); // Asia/Kolkata
        $mpdfService = $this->container->get('tfox.mpdfport');
        $response = $mpdfService->generatePdf($html);
        print_r(new \DateTime()); // Europe/London
        file_put_contents($pathToPdf, $response);
        chmod($pathToPdf,0777);`

**Comment by imajim** [comment]
hello,
it's normal. Mpdf update do 6.1 and this library call 6.0
https://github.com/mpdf/mpdf/issues/137
