### ISSUE TITLE
A tree builder without a root node is deprecated

### ISSUE THREAD

**Issue by Khatib-Abbas** [tasmanianfox/MpdfPortBundle#37]
i have this issue. since Symfony 4.2 and will not be supported anymore in 5.0.
 ›     $treeBuilder = new TreeBuilder();
 ›     $rootNode = $treeBuilder->root('t_fox_mpdf_port');
screen : https://prnt.sc/mf5k4f

**Comment by thelem** [comment]
I can see a fix for this has been committed, but there hasn't been a release for some time and I'm not even clear if 2.0.0 is a proper release. If it is, please can you tag a 2.0.1 including the latest commits?

**Comment by tasmanianfox** [comment]
Yes, thanks for reminder.
Created a release `2.0.1`.
