### ISSUE TITLE
Incompatibility with php 7.4

### ISSUE THREAD

**Issue by Zoopme** [tasmanianfox/MpdfPortBundle#40]
Hi @tasmanianfox, 

Is it possible to update composer.json to support php 7.4 ?

`    - mpdf/mpdf v7.1.9 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your php version (7.4.13) does not satisfy that requirement.
    - tfox/mpdf-port-bundle 2.0.0 requires mpdf/mpdf ^7.0 -> satisfiable by mpdf/mpdf[v7.1.9].
`

Thanks for your reply!

**Comment by Zoopme** [comment]
Created pull request #41

**Comment by tasmanianfox** [comment]
Hello,

Thanks for pull request!

I changed it slightly to allow all 8.*.* versions of mpdf. Unfortunately, cannot test it at the moment, but it must work fine.

**Comment by Zoopme** [comment]
Much appreciated! 
Thank you.
